export const INCREMENT = 'INCREMENT';

export const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
export const INCREMENT_ASYNC_SUCCESS = 'INCREMENT_ASYNC_SUCCESS';
export const INCREMENT_ASYNC_FAILURE = 'INCREMENT_ASYNC_FAILURE';
