export const CREATE_LEAGUE = 'CREATE_LEAGUE';
export const CREATE_LEAGUE_SUCCESS = 'CREATE_LEAGUE_SUCCESS';

export const FETCH_LEAGUES = 'FEATCH_LEAGUES';
export const FETCH_LEAGUES_SUCCESS = 'FETCH_LEAGUES_SUCCESS';
