export const CREATE_LEAGUE = 'CREATE_LEAGUE';
export const CREATE_LEAGUE_SUCCESS = 'CREATE_LEAGUE_SUCCESS';

export const FETCH_LEAGUES = 'FEATCH_LEAGUES';
export const FETCH_LEAGUES_SUCCESS = 'FETCH_LEAGUES_SUCCESS';

export const JOIN_TO_LEAGUE = 'JOIN_TO_LEAGUE';
export const JOIN_TO_LEAGUE_SUCCESS = 'JOIN_TO_LEAGUE_SUCCESS';

export const FETCH_LEAGUE_DETAILS = 'FETCH_LEAGUE_DETAILS';
export const FETCH_LEAGUE_DETAILS_SUCCESS = 'FETCH_LEAGUE_DETAILS_SUCCESS';
